# clusters/on-premises/minio/tenant/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio-tenant-credentials
  namespace: minio-tenant # Namespace onde o tenant será criado
type: Opaque
stringData:
  # Credenciais de acesso raiz para o MinIO
  # Use senhas fortes e geradas aleatoriamente
  MINIO_ROOT_USER: "minio-admin"
  MINIO_ROOT_PASSWORD: "c9n549l3."

