# apps/minio-operator.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/minio/operator.git' # Repositório oficial
    targetRevision: v7.0.1 # Use a versão estável mais recente
    path: . # Instala a partir da raiz do repositório
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: minio-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

